# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: affirm/grpc/fixtures/v1/interface.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'affirm/grpc/fixtures/v1/interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from affirm.grpc.fixtures.v1 import messages_pb2 as affirm_dot_grpc_dot_fixtures_dot_v1_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'affirm/grpc/fixtures/v1/interface.proto\x12\x17\x61\x66\x66irm.grpc.fixtures.v1\x1a&affirm/grpc/fixtures/v1/messages.proto2\x8e\x04\n\x0fGrpcTestService\x12k\n\x0cReflectReqId\x12,.affirm.grpc.fixtures.v1.ReflectReqIdRequest\x1a-.affirm.grpc.fixtures.v1.ReflectReqIdResponse\x12\x65\n\nRaiseError\x12*.affirm.grpc.fixtures.v1.RaiseErrorRequest\x1a+.affirm.grpc.fixtures.v1.RaiseErrorResponse\x12_\n\x08\x42locking\x12(.affirm.grpc.fixtures.v1.BlockingRequest\x1a).affirm.grpc.fixtures.v1.BlockingResponse\x12\x65\n\nBlockingV2\x12*.affirm.grpc.fixtures.v1.BlockingV2Request\x1a+.affirm.grpc.fixtures.v1.BlockingV2Response\x12_\n\x08Validate\x12(.affirm.grpc.fixtures.v1.ValidateRequest\x1a).affirm.grpc.fixtures.v1.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'affirm.grpc.fixtures.v1.interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCTESTSERVICE']._serialized_start=109
  _globals['_GRPCTESTSERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
