# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: affirm/grpc/fixtures/v1/messages.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'affirm/grpc/fixtures/v1/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&affirm/grpc/fixtures/v1/messages.proto\x12\x17\x61\x66\x66irm.grpc.fixtures.v1\"9\n\x13ReflectReqIdRequest\x12\x15\n\x08question\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_question\"4\n\x14ReflectReqIdResponse\x12\x12\n\x05reqid\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_reqid\"1\n\x11RaiseErrorRequest\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"2\n\x12RaiseErrorResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"7\n\x0f\x42lockingRequest\x12\x16\n\tblocktype\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_blocktype\".\n\x10\x42lockingResponse\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\"9\n\x11\x42lockingV2Request\x12\x16\n\tblocktype\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_blocktype\"0\n\x12\x42lockingV2Response\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\"M\n\x0fValidateRequest\x12:\n\x07message\x18\x01 \x01(\x0b\x32).affirm.grpc.fixtures.v1.ValidatedMessage\"N\n\x10ValidateResponse\x12:\n\x07message\x18\x01 \x01(\x0b\x32).affirm.grpc.fixtures.v1.ValidatedMessage\"\x81\x01\n\x10ValidatedMessage\x12\x1b\n\x0erequired_field\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x34\n\x04\x65num\x18\x04 \x01(\x0e\x32!.affirm.grpc.fixtures.v1.TestEnumH\x01\x88\x01\x01\x42\x11\n\x0f_required_fieldB\x07\n\x05_enum*K\n\x08TestEnum\x12\x19\n\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x11\n\rTEST_ENUM_ONE\x10\x01\x12\x11\n\rTEST_ENUM_TWO\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'affirm.grpc.fixtures.v1.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTENUM']._serialized_start=788
  _globals['_TESTENUM']._serialized_end=863
  _globals['_REFLECTREQIDREQUEST']._serialized_start=67
  _globals['_REFLECTREQIDREQUEST']._serialized_end=124
  _globals['_REFLECTREQIDRESPONSE']._serialized_start=126
  _globals['_REFLECTREQIDRESPONSE']._serialized_end=178
  _globals['_RAISEERRORREQUEST']._serialized_start=180
  _globals['_RAISEERRORREQUEST']._serialized_end=229
  _globals['_RAISEERRORRESPONSE']._serialized_start=231
  _globals['_RAISEERRORRESPONSE']._serialized_end=281
  _globals['_BLOCKINGREQUEST']._serialized_start=283
  _globals['_BLOCKINGREQUEST']._serialized_end=338
  _globals['_BLOCKINGRESPONSE']._serialized_start=340
  _globals['_BLOCKINGRESPONSE']._serialized_end=386
  _globals['_BLOCKINGV2REQUEST']._serialized_start=388
  _globals['_BLOCKINGV2REQUEST']._serialized_end=445
  _globals['_BLOCKINGV2RESPONSE']._serialized_start=447
  _globals['_BLOCKINGV2RESPONSE']._serialized_end=495
  _globals['_VALIDATEREQUEST']._serialized_start=497
  _globals['_VALIDATEREQUEST']._serialized_end=574
  _globals['_VALIDATERESPONSE']._serialized_start=576
  _globals['_VALIDATERESPONSE']._serialized_end=654
  _globals['_VALIDATEDMESSAGE']._serialized_start=657
  _globals['_VALIDATEDMESSAGE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
